services:
  searxng:
    image: searxng/searxng:2025.8.12
    restart: unless-stopped
    environment:
      SEARXNG_SETTINGS_PATH: /etc/searxng/settings.yml
      PYTHONWARNINGS: "ignore::DeprecationWarning"
    volumes:
      - searxng_etc:/etc/searxng
      - searxng_data:/var/lib/searxng
      - ./limiter.toml:/etc/searxng/limiter.toml:ro
    expose:
      - "8080"

  nginx:
    image: nginx:1.27-alpine
    restart: unless-stopped
    depends_on:
      - searxng
    ports:
      - "127.0.0.1:8888:8888"
    volumes:
      - ./nginx:/etc/nginx/conf.d:ro
    command: ["nginx", "-g", "daemon off;"]

  gabesearch-mcp:
    build:
      context: .
      dockerfile: Dockerfile
    stdin_open: true
    tty: true
    environment:
      - SEARX_URL=http://host.docker.internal:8888/search
      - TOP_K=3
      - QUERIES=5
      - PER_PAGE_CHARS=3000
      - TOTAL_CHARS=15000

volumes:
  searxng_etc:
  searxng_data:
