services:
  searxng:
    image: searxng/searxng:latest
    restart: unless-stopped
    ports:
      - "8888:8080"
    environment:
      - BASE_URL=http://localhost:8888/
      - INSTANCE_NAME=LocalSearxNG
    volumes:
      - ./searxng-config:/etc/searxng:ro

  gabesearch-mcp:
    build: .
    stdin_open: true
    tty: true
    environment:
      - SEARX_URL=http://host.docker.internal:8888/search
      - TOP_K=3
      - QUERIES=5
      - PER_PAGE_CHARS=20000
      - TOTAL_CHARS=100000
      - QDRANT_HOST=host.docker.internal
      - QDRANT_PORT=6333
      - WEB_CACHE_COLLECTION=web-cache
      - WEB_CACHE_TTL_DAYS=10

  qdrant:
    image: qdrant/qdrant:latest
    restart: unless-stopped
    ports:
      - "6333:6333"
    volumes:
      - ./qdrant-data:/qdrant/storage

