services:
  searxng:
    image: searxng/searxng:latest
    restart: unless-stopped
    ports:
      - "8888:8080"
    environment:
      - BASE_URL=http://localhost:8888/
      - INSTANCE_NAME=LocalSearxNG
    volumes:
      - ./searxng-config:/etc/searxng:ro

  qdrant:
    image: qdrant/qdrant:latest
    restart: unless-stopped
    ports:
      - "6333:6333"
    volumes:
      - ./qdrant-data:/qdrant/storage

  gabesearch-mcp:
    build: .
    restart: unless-stopped
    stdin_open: true
    tty: true
    environment:
      # Use service DNS names inside the compose network
      - SEARX_URL=http://searxng:8080/search
      - TOP_K=3
      - QUERIES=5
      - PER_PAGE_CHARS=20000
      - TOTAL_CHARS=100000
      - QDRANT_HOST=qdrant
      - QDRANT_PORT=6333
      - WEB_CACHE_COLLECTION=web-cache
      - WEB_CACHE_TTL_DAYS=10
      - LOG_LEVEL=INFO
    volumes:
      # Persist HuggingFace model cache
      - hf-cache:/root/.cache/huggingface
    depends_on:
      - searxng
      - qdrant

volumes:
  hf-cache:
